### ISSUE TITLE
Support platform_common and ToolchainInfo

### ISSUE THREAD

**Issue by ostera** [bazelbuild/skydoc#100]
Hi!

I'm trying to use `skydoc` in some [rules I'm writing for ReasonML](https://github.com/ostera/rules_reason) but I'm having trouble with `platform_common` being undefined.

```
  File "external/com_github_ostera_rules_reason/reason/private/bs_module.bzl", line 127, in <module>
    providers = [platform_common.ToolchainInfo],
NameError: name 'platform_common' is not defined
```

From looking around I saw the fix for `provider` and I think I can add to the `rule_extractor.py` another stub for `platform_common` so that I can generate docs.

What do you think? :)

**Comment by laurentlb** [comment]
Yes, feel free to add more stubs.
We know it's brittle, so Skydoc is going to be rewritten in a much more robust way (cc @c-parsons).

**Comment by c-parsons** [comment]
Closing. Use Stardoc :)
