### ISSUE TITLE
Rewrite of Skydoc

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/skydoc#102]
We plan to rewrite Skydoc using a real Skylark interpreter (instead of Python).

**Comment by philipjameson** [comment]
Is there a timeline or anything for this? I have a few features I'd like to add, but it'd kind of suck if they were immediately obsoleted :)

**Comment by laurentlb** [comment]
@c-parsons has a prototype (see recent pull requests).
I would discourage you from doing any meaningful development on the Python code.

**Comment by philipjameson** [comment]
So looking through here: https://github.com/bazelbuild/skydoc/pull/105/commits/1946693b01c0e77615c7adb56a7d7bb943103c6d does that mean that all development is going to instead be done in the bazel repo?

**Comment by c-parsons** [comment]
In the short/medium term, yes. Long term we want to move the source code / packages to the skydoc repository (or alternatively the Starlark repository)
..but there's still a lot of work to do to separate the source out from bazel packages.

**Comment by c-parsons** [comment]
We've announced launch of Stardoc on `bazel-dev@googlegroups.com` and updated the documentation in https://skydoc.bazel.build
We'll follow up to make a release announcement alongside a Bazel release, and then remove skydoc and its documentation.

**Comment by dgoldstein0** [comment]
so... this shipped?  should this issue be closed?

**Comment by c-parsons** [comment]
Yeah -- sure. I was keeping it open for a release annoucement and subsequent removal of old-Skydoc, but I can track that elsewhere.
