### ISSUE TITLE
Ability to pass in custom templates to Stardoc

### ISSUE THREAD

**Issue by jerechua** [bazelbuild/skydoc#120]
The output of Stardoc is rather prescriptive and not modifiable. I would like to be able to restructure the generated docs in such a way that looks similar to my already existing documentation.

**Comment by c-parsons** [comment]
One thought I had in this area: What if Stardoc could optionally output in proto format? That would allow for extensive customization of the output format without prescribing a templating contract.

**Comment by jerechua** [comment]
By output in a proto format, you mean dumping the doc related AST into a proto? That would be quite useful!

It would also allow way more flexibility in doing things like splitting functions up into multiple files.

**Comment by laurentlb** [comment]
Output to protos would be useful.
Do you think it would fit in this one? https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/builtin.proto

We use it to export Starlark builtins.

**Comment by jerechua** [comment]
It looks like it would fit `Value` pretty well, but I think the package might be a bit confusing.

package name aside, WDYT about:

```
message UserDefinedFunction {
  repeated Value func = 1;
}
```

Then for:

```
def foo_func(foo, bar=2,*arg, **kwarg):
  """foo_func description.

  Args:
    foo: {str} foo description.
    bar: {int} bar description.
    *arg: {List[Any]} arg description.
    **kwarg: {Dict[Any,Any]} kwarg description.
  """
  pass
```

This generates

```
func {
  name: "foo_func"
  type: "macro"  // "macro", "rule", or "provider"
  doc: "foo_func description."
  ApiContext: BZL
  callable {
    param {
      name: "foo"
      type: "str"  // only if set to {str}, "" otherwise.
      doc: "foo description."
      is_mandatory: true
    }
    param {
      name: "bar"
      type: "int"
      doc: "bar description."
      default_value: 2
    }
    param {
      name: "*arg"
      type: "List[Any]"
      doc: "arg description."
      is_star_arg: true
    }
    param {
      name: "bar"
      type: "Dict[Any,Any]"
      doc: "kwarg description."
      is_star_star_arg: true
    }
  }
}
```

This would also need us to be able to parse the type from AST which is #48

**Comment by laurentlb** [comment]
Looks good!

We can rename `Builtins` message to `Environment` to make it more general.

**Comment by c-parsons** [comment]
Looks good to me!

**Comment by c-parsons** [comment]
We plan on addressing this in late Q2 / early Q3.

**Comment by c-parsons** [comment]
This is "done", but still needs to be documented. This will be documented and announced for next release.
