### ISSUE TITLE
Require code reviews

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/skydoc#128]
I submitted https://github.com/bazelbuild/skydoc/commit/1cdb612e31448c2f6eb25b8aa67d406152275482 by accident: I thought I was pushing in my fork. So the code got submitted without any review. Based on the history, it's not the first commit pushed without a PR. Can we prevent that?

**Comment by dslomov** [comment]
Sorry for dropping this on the floor; added @laurentlb  and @c-parsons as admins, and protected `master` requiring at least one code review from CODEOWNERS including admins.

**Comment by dslomov** [comment]
(admins can tweak the setting further afaiu, please tell me if that is not the case)
