### ISSUE TITLE
Problems when migrating rules_rust to stardoc

### ISSUE THREAD

**Issue by mfarrugi** [bazelbuild/skydoc#134]
1. There are no `bzl_library` in @bazel_tools or @bazel_skylib, which should be the most common dependencies. This makes porting downstream rules more difficult.

I needed to comment out the loads in rust/private/rustc.bzl and uncomment lines in docs/all.bzl to generate the docs, I imagine this worked because we don't have type dependencies.

2. [docs/all.bzl](https://github.com/bazelbuild/rules_rust/blob/e8de7108ad5d75607159d47ae69c380a578f932d/docs/all.bzl) needed to use import aliases to work, which is not what https://skydoc.bazel.build/docs/generating_stardoc.html suggests.

Other raw TODO`s in https://github.com/bazelbuild/rules_rust/pull/174:
```
docs/all.bzl
13:#    # TODO(stardoc): yeah okay
        # external/docs/all.bzl:7:1: file '@io_bazel_rules_rust//rust:rust.bzl' does not contain symbol 'rust_benchmark ' (did you mean 'rust_benchmark'?)
        # _rust_benchmark = "rust_benchmark ",

docs/BUILD
12:        "rust_benchmark",  # TODO(stardoc): no lint against absent symbols

rust/private/rust.bzl
195:    # TODO(stardoc): How do we provide additional documentation to an inherited attribute?
```

**Comment by dgoldstein0** [comment]
just stumbled onto this aliias problem.  It looks like docs are generated, but all the names are <unknown name> without the aliasing which is rather unhelpful

**Comment by c-parsons** [comment]
Is aliasing for purpose of documenting a pain? Can you elaborate on the issues you're encountering?
(I would expect aliasing only needs to be used to fully combine symbols originally defined in several files)
