### ISSUE TITLE
Fix the naming hell: skydoc, skylar, stardoc, skylark_doc ...

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/skydoc#135]
# The problem

The names of the rules and various `.bzl` files involved in the `skylib` repository and the `skydoc` repository are way too confusing.

The relatively recent renaming from `skylark` to `starlark` exacerbated the situation.

For example, `skydoc` and `stardoc` sound virtually the same to me. I was wondering why they both existed. Shouldn't `stardoc` replace `skydoc`? Why both?

# Desirable situation

As a Bazel rule developer and user, I would like to have a very thin and consistently named API, and the use of `star` over `sky` whenever possible to be eventually consistent with the renaming.

The old `sky`-based names can still be exported as deprecated to maintain backward compatibility.

**Comment by c-parsons** [comment]
`stardoc` will replace `skydoc`. We're in a brief migration period (~1 release) where we have both, and have documentation available for both. Stardoc isn't a drop-in replacement for Skydoc, so this is meant as a convenience to users.

**Comment by qzmfranklin** [comment]
Thanks for the explanation.

I am happy with knowing these. Closing.
