### ISSUE TITLE
stardoc rule: cannot have bzl_library dependencies when declared in a bazel-skylib package

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/skydoc#137]
Cannot use the [`stardoc` rule](https://github.com/bazelbuild/skydoc/blob/82fdbfe797c6591d8732df0c0389a2b1c3e50992/stardoc/stardoc.bzl) inside of https://github.com/bazelbuild/bazel-skylib with[`bzl_library` rule](https://github.com/bazelbuild/bazel-skylib/blob/c00ef493869e2966d47508e8625aae723a4a3054/bzl_library.bzl) dependencies.

The `stardoc` rule complains that the `bzl_library` does not have mandatory provider `StarlarkLibraryInfo`.

**Comment by laszlocsomor** [comment]
Context: I'm trying to generate Stardoc for `maprule`, see https://github.com/bazelbuild/bazel-skylib/pull/86.

Workaround for now is not to import any other bzl modules from skylib so I need no `bzl_library`, and just pass `maprule.bzl` to `stardoc.input`.

**Comment by laszlocsomor** [comment]
@c-parsons : is anyone working (on planning to work) on this bug?

**Comment by c-parsons** [comment]
Ha, I lost track of this bug, but I happen to be actively working on placing stardoc targets in `bazel-skylib` (and improving the documentation)

The solution is the `--experimental_remap_main_repo` flag which @dkelmer has recently implemented and is working to make default behavior. For the time being, we can use this flag manually and ad-hoc to generate docs.

**Comment by dkelmer** [comment]
I think you could add a project bazelrc with the flag so that you don't
need to pass it manually when generating documentation
