### ISSUE TITLE
Download stardoc binary as a prebuilt?

### ISSUE THREAD

**Issue by scele** [bazelbuild/skydoc#139]
Using stardoc currently requires downloading all bazel sources (takes about 1 minute just to download on my machine), and compiling stardoc with a java toolchain (I didn't verify but I suspect that this adds a requirement that one must have java runtime installed on the system, while normally bazel would not require it for non-java workspaces).

Have you considered publishing prebuilt linux+mac+windows binaries of stardoc, for example on the github.com/bazelbuild/bazel/releases page? That would make stardoc much lighter weight to adopt I think!

**Comment by c-parsons** [comment]
Fixed in https://github.com/bazelbuild/skydoc/commit/45ae581e07e951cc9863007bddeadab89a883f2c
