### ISSUE TITLE
Break rule signature into multiple lines. 

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/skydoc#142]
By using a single line, markdown creates a scrollable block that doesn't show the complete signature. Breaking the signature into multiple forces markdown to display the complete block instead.

Difference between:

<pre>ios_application(name, app_icons, bundle_id, bundle_name, entitlements, entitlements_validation, extensions, families, frameworks, infoplists, ipa_post_processor, launch_images, launch_storyboard, linkopts, minimum_os_version, provisioning_profile, settings_bundle, strings, version, watch_application, deps)</pre>

and

<pre>
ios_application(name, app_icons, bundle_id, bundle_name, entitlements,
entitlements_validation, extensions, families, frameworks, infoplists,
ipa_post_processor, launch_images, launch_storyboard, linkopts,
minimum_os_version, provisioning_profile, settings_bundle, strings, version,
watch_application, deps)
</pre>

**Comment by marcohu** [comment]
On a quick glance, it seems there is a single method in `MarkdownUtil.java` that does build the signature strings. 

The following works for me and might serve as a starting point for a proper fix. Please let me know if you should welcome a patch.

```java
  private String summary(String functionName, List<String> paramNames) {
    Deque<List<String>> lines = wrap(functionName, paramNames, 75);
    List<String> paramLinks = lines
      .stream()
      .map(params -> params
        .stream()
        .map(param -> String.format("<a href=\"#%s-%s\">%s</a>", functionName, param, param))
        .collect(Collectors.joining(", ")))
      .collect(Collectors.toList());
    return String.format(
      "%s(%s)",
      functionName,
      Joiner.on(String.format(",\n%1$" + (functionName.length() + 1) + "s", "")).join(paramLinks)
    );
  }

  private Deque<List<String>> wrap(String functionName, List<String> paramNames, int maxLineLength) {
    Deque<List<String>> lines = new ArrayDeque<>();
    lines.addLast(new ArrayList<>());

    int leading = functionName.length();
    int length = leading;

    for (String paramName : paramNames) {
      length += paramName.length() + 2;
      if (length > maxLineLength) {
        length = leading + paramName.length() + 2;
        lines.addLast(new ArrayList<>());
      }
      lines.getLast().add(paramName);
    }
    return lines;
  }
```

**Comment by c-parsons** [comment]
A patch would be welcome - feel free to add me as a reviewer. Thanks!

**Comment by marcohu** [comment]
I've submitted https://github.com/bazelbuild/bazel/pull/9240. I was not able to add you as a reviewer. 

I don't know what the best wrapping line length might be. I was wondering whether making the it configurable would be worthwhile. For now 80 columns seems like a safe bet.
