### ISSUE TITLE
Allow different markdown flavors (or standardize in the Github flavor)

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/skydoc#143]
Currently Stardoc generates an HTML table for displaying the attributes. This prevents automatic conversion of backtics and Markdown links in attribute descriptions, making them look like this:

<table class="params-table">
  <colgroup>
    <col class="col-param" />
    <col class="col-description" />
  </colgroup>
  <tbody>
    <tr id="tvos_extension-version">
      <td><code>version</code></td>
      <td>
        <a href="https://bazel.build/docs/build-ref.html#labels">Label</a>; optional
        <p>
          An `apple_bundle_version` target that represents the version for this target. See
[`apple_bundle_version`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-general.md?cl=head#apple_bundle_version).
        </p>
      </td>
    </tr>
  </tbody>
</table>

The Github flavor of markdown, which supports markdown descriptions for attributes, for creating tables looks like this:

| Attribute  | Description                                                  |
| ---------- | ------------------------------------------------------------ |
| `version`  | [Label](https://bazel.build/docs/build-ref.html#labels); optional<br/>An `apple_bundle_version` target that represents the version for this target. See [`apple_bundle_version`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-general.md?cl=head#apple_bundle_version). |

**Comment by c-parsons** [comment]
See https://github.com/bazelbuild/skydoc/issues/69 for details on why our layout looks like this.
So right now you can get attribute link support via HTML tags such as using `<a href`
