### ISSUE TITLE
Stop using @com_google_protobuf//:protobuf.bzl

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/skydoc#145]
https://groups.google.com/d/msg/bazel-dev/GOum-5rjTzE/yo110DAzAQAJ

> protobuf.bzl is (and has always been) documented as being internal-only: https://github.com/protocolbuffers/protobuf/blob/master/protobuf.bzl#L235-L237

https://github.com/bazelbuild/skydoc/blob/4ea7b8257d11ac33eef7e9daadbedbfe375d9236/skydoc/BUILD#L5

**Comment by laurentlb** [comment]
cc @brandjon 
What's the recommendation for a `py_proto_library` rule?

**Comment by c-parsons** [comment]
We will also need to cleanup bazel's packages to prevent a need for dependency on protoc via @io_bazel

$ ```bazel query "somepath(test/..., @io_bazel//src/main/protobuf/...)"```

```
//test:stardoc_self_gen_test
//stardoc:stardoc_doc.md
//stardoc:stardoc_doc
@io_bazel//src/main/java/com/google/devtools/build/skydoc:skydoc
@io_bazel//src/main/java/com/google/devtools/build/skydoc:skydoc_lib
@io_bazel//src/main/java/com/google/devtools/build/skydoc/fakebuildapi/android:android
@io_bazel//src/main/java/com/google/devtools/build/lib:packages-internal
@io_bazel//src/main/protobuf:build_java_proto
```

**Comment by c-parsons** [comment]
(And to deal with the Skydoc py proto library dependency, we can just delete Skydoc... :))

**Comment by c-parsons** [comment]
This is no longer a dependency of bazelbuild/stardoc.
