### ISSUE TITLE
Remove dependency on protoc

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/skydoc#147]
Both Skydoc and Stardoc pull in a dependency on `@com_google_protobuf`. We should delete Skydoc to remove that dependency, and cleanup bazel's packages to prevent a need for dependency on protoc via `@io_bazel`

**Comment by laurentlb** [comment]
https://github.com/bazelbuild/skydoc/issues/145

**Comment by c-parsons** [comment]
Whoops. ty. closed as duplicate.
