### ISSUE TITLE
stardoc has no html output support

### ISSUE THREAD

**Issue by dgoldstein0** [bazelbuild/skydoc#148]
https://skydoc.bazel.build/docs/getting_started_stardoc.html is supposedly a replacement for skydoc, but it has no support for outputting a whole html site - the only output format is "markdown" - which is mostly html, but has no css or navigation elements or index page.  For stardoc to be usable as a replacement for skydoc, some replacement for the html output would be ideal.

**Comment by c-parsons** [comment]
What exactly are you looking for in your HTML output? Is this something your team needs?

Piping the markdown output to a markdown-to-html converter binary can get you what you need, if all you're looking for is HTML.

FWIW We've had some discussions about developing Stardoc output to meet the needs of various teams with different requirements, and the current proposal is to provide a rich proto output for which someone else could contribute a proto-to-html, proto-to-markdown, or proto-to-whatever format.

if you'd like something sooner for HTML output, I'd encourage you to please contribute! (Most rules teams I have talked to have cared primarily about markdown) I can provide pointers if need be.

**Comment by dgoldstein0** [comment]
right now I'm still using skydoc - though I started playing with stardoc and love it's ability to use doc field from attr's and the documentation field of each rule().

The trouble is, right now my configuration looks like:

```
package(default_visibility = ["//visibility:public"])
load("@io_bazel_skydoc//skylark:skylark.bzl", "skylark_doc")

skylark_doc(
    name = "autogen_docs",
    srcs = [
        "//build_tools/static_build:autogen_docs",
    ],
    format = "html",
    site_root = "/bazel_static",
    strip_prefix = "build_tools/static_build",
)
```
```# in build_tools/static_build/BUILD
skylark_library(
    name = "autogen_docs",
    srcs = glob(
        [
            "*.bzl",
        ],
        exclude = [
            "util.bzl",
        ],
    ),
)
```

so I'm getting a whole static website out the other end of skydoc and handing that off to a system to serve it.  with the new stardoc rules I have to figure out how to compose them into my own website.  I suppose it's doable; but:
- I have to manually declare each page as it's own stardoc rule, whereas with skydoc I get all my pages for free via a simple glob().  This isn't a big problem as I only have 4 such files anyway, but it's annoying.
- I don't get an overview page
- no nav (I actually dislike the existing skydoc nav anyway - would like to include macros).

I suppose I'd like more customization capability, so really I suppose I'm asking for the overview and nav parts.  Perhaps what we really need is just an example of how to do this all with stardoc, that could then be customized to individual needs.

**Comment by danwos** [comment]
I'm also searching for a way to embedded data from bazel-rules into websites, or better to show it inside a sphinx-project with rst-support in the docstrings.

Even it will be a new approach for @dgoldstein0, using sphinx would give you all the feature you need (e.g. create a whole website around the bazel rules).
And stardoc could focus on providing a focused API documentation.

However, I started a small discussion for this topic on the bazel-discuss mailing list. 
Feel free to take part: https://groups.google.com/forum/?nomobile=true#!topic/bazel-discuss/YgbIWmgsDuY

**Comment by c-parsons** [comment]
Stardoc now supports custom output format as well as proto output format (for integration into your own custom renderer, if that's what you'd like)

Please feel free to re-open if you had something else in mind, or file another FR for something more specific.
