### ISSUE TITLE
Create skydoc.bazel.io and add push job for Skydoc site

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/skydoc#15]
This is a follow-up to #14:

* Set up skydoc.bazel.io.
* Add the Skydoc site to the automated push job for publishing the site.

Damien - feel free to set this up when you get a chance. :)

**Comment by damienmg** [comment]
@laszlocsomor have sent the change for skydoc.bazel.io and I just created the skydoc.bazel.io bucket on google cloud. You can copy the site using gsutil to gs://skydoc.bazel.io/.

I will be setting the automatic sync later (might take more time as I want to finish something this week and will be OOO for 2 weeks after that).

**Comment by davidzchen** [comment]
Thanks!

I have copied the site files to `gs://skydoc.bazel.io/`, but it looks like http://skydoc.bazel.io currently points to the Bazel site. Is there another change we need to make to have it point to serve the files in `gs://skydoc.bazel.io/`?

**Comment by laszlocsomor** [comment]
@davidzchen, Damien knows this better than I do. He's returning from vacation next week. FYI, Monday we're all out.

**Comment by davidzchen** [comment]
Understood. No problem.

**Comment by damienmg** [comment]
Ok the issue was a quota limit on Google Cloud Load Balancer. That's the reason skydoc wasn't served. I updated the configuration and it should be up in a few hours.

**Comment by davidzchen** [comment]
skydoc.bazel.io is still serving the Bazel site. :(

**Comment by damienmg** [comment]
Live and with SSL finally :)

**Comment by davidzchen** [comment]
Awesome! \o/ Thanks for taking care of this!
