### ISSUE TITLE
NameError: name 'java_common' is not defined

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/skydoc#154]
We're encountering the following error with skydoc 0.2.0 on Bazel 0.21 on rules that use `java_common`:
```
NameError: name 'java_common' is not defined
```
The rule has the following `attrs` entry
```
        "_jdk": attr.label(
            providers = [java_common.JavaRuntimeInfo],
            default = Label("@bazel_tools//tools/jdk:current_java_runtime"),
        ),
```
and refers to `java_common` in its implementation
```
    java_runtime = ctx.attr._jdk[java_common.JavaRuntimeInfo]
```
The rule itself works fine, however including it as a `srcs` entry to `skylark_doc` raises the `NameError` above.

**Comment by c-parsons** [comment]
This should be fixed (and we have an e2e test verifying java_common.JavaRuntimeInfo in particular)
