### ISSUE TITLE
Release skydoc as python package on PyPi

### ISSUE THREAD

**Issue by danwos** [bazelbuild/skydoc#164]
As skydoc is pure python code, it would be great to release it on PyPI.

I'm currently developing a [sphinx-bazel  extension](https://sphinx-bazel.readthedocs.io), which automatically parses Bazel files and make its content and especially the docstrings available inside a sphinx based documentation. 

As skydoc provides already awesome functions to parse .bzl-files for rules, macros and loads, it would be great if there is an easy way to reuse this work.
The "normal" way would be to define "skydoc" as dependency in my ``setup.py`` file and use the needed code via import statements like ``from skydoc.rule_extractor import RuleDocExtractor``

However, this is currently not possible as there is no official release available (in terms of the python ecosystem). Other options like copy/fork code-parts to my repo, force the user to clone needed code, are also not so nice.

So is it possible to
1. Create a ``setup.py`` file
2. Set a version
3. Release it on PyPI?

**Comment by c-parsons** [comment]
skydoc (the python tool) is deprecated and will be removed soon. We're pushing for users to migrate to Stardoc (which is written in Java, with source code living under bazelbuild/bazel).

See the [current doc page](https://skydoc.bazel.build) for details.
