### ISSUE TITLE
io_bazel version checking

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/skydoc#170]
Stardoc functionality is tightly tied to the version of the Stardoc java binary itself, which lives in `@io_bazel`. A user which depends on a new version of the `skydoc` repository might accidentally depend on a very old version of `@io_bazel`, and thus be seeing a very different feature set than what they should expect given the version of `skydoc`.

We should attempt to warn when a user is depending on an old version of `@io_bazel`.

**Proposal:**
In `io_bazel`, add a bzl file which contains a version number constant that `skydoc` checks. If the version number is much older than what is acceptable for the current version of `skydoc`, emit a warning that the user may want to update their dependency.

**Comment by laurentlb** [comment]
We should discuss with the external repository team whether we should do that.
(every repository has the same problem)

**Comment by c-parsons** [comment]
I did discuss with @dkelmer and she said this may be a decent option, with a couple of caveats.

1. A version mismatch should lead to a warning and not an error
2. Warnings are not ideal and not helpful for a number of rules (as they may be from a user's dependencies as opposed to owned by the user), but Stardoc is a bit different, in that Stardoc targets should not really be built unless the user wants to generate documentation explicitly.

Anyone else we should loop in? :)

**Comment by c-parsons** [comment]
**Proposal 2:**
Check-in the Stardoc binary into this repository, and thus eliminate the dependency on `@io_bazel` for users of Stardoc.

**Comment by dkelmer** [comment]
After a second discussion, I am in favor of proposal 2 :) 
I think that stardoc is pretty unique in that it depends on sources from the bazel tree and so bundling a prebuilt jar is a good solution to severing that dependency.

**Comment by laurentlb** [comment]
cc @fweikert 
Are there any concerns with checking in a binary file?

**Comment by fweikert** [comment]
No objections, except that it would be more maintenance for you.
