### ISSUE TITLE
Support pulling docs from multiple files and/or support macros wrapping rules

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/skydoc#178]
Right now the current `stardoc` rule is a 1:1 mapping of input files to output files, so all symbols must come from that one file or dummy files reexporting things from that one file must be used to generate things.

In some of our projects, we end up with a single `.bzl` to provide a _collection_ of things (say the `ios_*` rules).  But for _reasons_, so of those things may be macros as implementation details to do some preprocessing/validation before handing things off to the real (private) rule(s).

This means the private rule actually is what has all the attributes defined, and the macro provide far less info; it likely only lists a subset of the attributes, macros have no knowledge of the types for the attributes, the defaults can also still be on the rule instead of the macro.

One way to solve this might be to support pulling the docs from multiple files so you can pull get the private rule (likely with the same name for reporting in queries, etc.) for some part, but the simpler things come out of the main file.

Going along with that might be the need to say generate the docs from one symbol but expose it as another name (for the macro case) sorta like how a `load()` and import a symbol with a different name.

I believe skylib has some examples of the macros wrapping rules for "reasons".  One easier case on our end is something like [`apple_genrule`](https://github.com/bazelbuild/apple_support/blob/master/rules/apple_genrule.bzl).

**Comment by aiuto** [comment]
Supporting wrappers is even more important now that outputs map has gone away and each must be declared. Rules that used to produce a few implicit outputs based on the name now tend to have a wrapper to generated the default strings for the output files to pass to the real rule implementation.

**Comment by c-parsons** [comment]
to clarify, wrappers (that is, macros that wrap rules) *are* supported, we just don't handle the convenience of documenting them that well. 
aiuto@, is your remark better suited to https://github.com/bazelbuild/skydoc/issues/190 ?

**Comment by c-parsons** [comment]
Current proposal for fixing this is described in https://github.com/bazelbuild/stardoc/issues/27

Let me know if indeed this is a separate issue, or if that proposal wouldn't work for your use case (otherwise this seems like a duplicate bug)
