### ISSUE TITLE
Args that use <var-name> in comment descriptions are lost in the rendered markdown file 

### ISSUE THREAD

**Issue by irataxy** [bazelbuild/skydoc#186]
Angle brackets in source code comments for args are lost in the generated html file when used in tables. Stardoc uses HTML tables for args.

For example, this comment in the `Args`: section of a .bzl file:

`name: Target name. The package name is derived from this name as <name>-0.exe.`

Will lose the `<name>` portion in the rendered HTML table. Using markdown code ticks (`) doesn't help as markdown will not appear in an HTML table either.

**Comment by c-parsons** [comment]
Technically this will be fixed with https://github.com/bazelbuild/skydoc/pull/212

**Comment by deeglaze** [comment]
I saw #212 was merged, so I've updated to c7bbde29 but I still see <name> unescaped in descriptions. For example, my doc string for a macro documents `name` as "name: Target name for will be <name>_enclave." but still the output markdown contains HTML tables without escaping the < and >. This ends up ruining the rendered document.
