### ISSUE TITLE
Rename repository to stardoc.

### ISSUE THREAD

**Issue by tmc** [bazelbuild/skydoc#187]

**Comment by c-parsons** [comment]
actively working on this. [bazelbuild/stardoc](https://github.com/bazelbuild/stardoc) is up with migrated source code, but there are additional steps before calling this complete.

See [design document](https://docs.google.com/document/d/1HrUHFyfU0HpWG6F6ws-8zESZ16h4N7p8WsOPR9iqJbo/)
