### ISSUE TITLE
Published documentation is out-of-date

### ISSUE THREAD

**Issue by bmuschko** [bazelbuild/skydoc#197]
The ["Getting Started" web page](https://skydoc.bazel.build/docs/getting_started_stardoc.html) references version 0.2.0 of Skydoc. However, version 0.3.0 has already been released in May and [the source file for the page](https://github.com/bazelbuild/skydoc/blob/master/site/docs/getting_started_stardoc.md#setup) has been switched to 0.3.0. I think the latest version of the documentation hasn't been published yet.

**Comment by c-parsons** [comment]
Oof. Nice catch and thank you. I'll get to this shortly.

**Comment by brandjon** [comment]
Related #49.

**Comment by c-parsons** [comment]
We've moved docs to [bazelbuild/stardoc](https://github.com/bazelbuild/stardoc), and they should be up to date.
