### ISSUE TITLE
Links to GitHub from documentation page still point to Skydoc

### ISSUE THREAD

**Issue by bmuschko** [bazelbuild/skydoc#198]
Now that Skydoc has been deprecated, I think it makes sense to change the links to Stardoc instead.

* https://github.com/bazelbuild/skydoc/blob/master/site/_includes/header.html#L8
* https://github.com/bazelbuild/skydoc/blob/master/site/_includes/drawer.html#L34-L35

**Comment by bmuschko** [comment]
Ah, I just realized that it is the same GitHub repository. Maybe it would make sense to rename the repository for more clarity.

**Comment by c-parsons** [comment]
Duplicate with https://github.com/bazelbuild/skydoc/issues/187
