### ISSUE TITLE
Extract and document default values for attributes

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/skydoc#2]
Add support for extracting default values for rule and macro attributes. Skylark rules generally provide this information, though for Macros, we could extract this information from default argument values from the AST.

**Comment by davidzchen** [comment]
Documenting default values for rule attributes is now supported. Still need to implement the same for macros.

**Comment by c-parsons** [comment]
(Closed as this is for Skydoc. The attached bug #238 is for tracking in Stardoc)
