### ISSUE TITLE
Markdown link syntax is uninterpreted in skydoc.bazel.build

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/skydoc#206]
This page includes markup for a link to generating_stardoc.html. Might be because the name of the page is misspelled as "geenrating".

More generally, what do you think of the idea of moving all skydoc.bazel.build content to markdown under a `docs` directory in this repository? This would make stardoc eat its own dogfood by presenting the same docs browsing experience it provides to its client rulesets.

**Comment by c-parsons** [comment]
Moved to docs/ under bazelbuild/stardoc
