### ISSUE TITLE
Support load() statements

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/skydoc#21]
Skylark sources that `load()` other Skylark sources is currently not supported, and references to `load()`ed symbols in the global scope result in errors.

Some possible approaches:
- Evaluate `load()` statements and create mock definitions of symbols in the global scope. See if we can do this using the stub for `load()`.
- Parse the label and evaluate the file that `load()` is pointing to.

Eventually, this problem (and other problems caused by incompatibility with Python) will be solved by Skylark-as-a-library.

**Comment by allevato** [comment]
Does the merged PR resolve this issue completely?

**Comment by davidzchen** [comment]
The merged PR is one step towards this but does not resolve this issue fully. We would still need to fully implement symbol resolution.

**Comment by alexeagle** [comment]
I assume the resolution of this issue would also fix this problem:

`basic.bzl`
```
base_attrs = {
  "data": attr.label_list(doc = "Important note")
}
```

`my_rule.bzl`
```
load("bazel.bzl", "base_attrs")
my_rule = rule(
attrs = dict(base_attrs, **{
  "another_attr": attr.string(doc = "Also important")
}))
```
