### ISSUE TITLE
Output template which uses markdown tables

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/skydoc#216]
Related: #69, https://github.com/bazelbuild/skydoc/issues/183

There's much inconsistency with how skydoc deals with escaping and formatting -- we should at the very least provide a basic set of output templates which circumvent the HTML table mess, and thus use pure markdown for all display.

**Comment by c-parsons** [comment]
@blossommojekwu @kendalllaneee This might be a great thing to incorporate into a "using custom templates" tutorial, as it would have real use aside from the purpose of being an example.

**Comment by alexeagle** [comment]
Tables render really wide on small screens. Why use them at all?

I guess for rules_nodejs we'll make this new template now. Here I have each rule as a level 4 header
https://github.com/alexeagle/rules_nodejs/blob/master/tools/stardoc/templates/rule.vm

On github it looks like
https://github.com/bazelbuild/rules_nodejs/wiki/scratch
And in github pages
https://alexeagle.github.io/rules_nodejs/Stylus.html

**Comment by c-parsons** [comment]
I'm glad you've crafted custom templates that work for you :) Certainly an approach that avoids tables is great.

I still propose that it would be nice to have an alternative to the default html-tables templates which uses a purer markdown approach.

We might also consider incorporating such options into the `stardoc` rule of stardoc.bzl. Currently this rule takes a `format` string attribute, which can be `markdown` or `proto`. (Lets ignore the fact that presently the `markdown` format is actually markdown with HTML tables).

We could provide an additional "pure markdown" option, which automatically points to a pure-markdown-tables solution. 
(We could also incorporate your "markdown-no-tables" solution, as well)

Food for thought. Obviously we don't want to be in the business of providing *too* many options (as it becomes a support burden), but 2-3 different alternatives might work well.

**Comment by alexeagle** [comment]
I think fewer first-party-maintained options is better. Why keep the tables one at all?

Of course Most important is confirming whether docs should be authored in markdown or html.
