### ISSUE TITLE
Render default attribute values for rule / aspect attributes

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/skydoc#238]
We render the default values for function parameters, but not for rule/aspect attributes

**Comment by c-parsons** [comment]
https://github.com/bazelbuild/skydoc/issues/2 tracks this for skydoc -- I will close that issue as it's pertaining to the deprecated binary.

**Comment by alexeagle** [comment]
Ping! I'm switching a big repository rule docs from macro to rule, and I'm losing the default values. Can I help with this?

**Comment by c-parsons** [comment]
Hi Alex,

You caught me actively working on this. Should be done in a couple of days (it would be sooner, but I'm in the midst of overhauling some of our test coverage to ensure this feature is appropriately tested as I roll it out)

Does that work for you?

**Comment by alexeagle** [comment]
yes, that's great, thank you!

**Comment by c-parsons** [comment]
Hey, 

Sorry for the further delay.
I'm in the process of migrating Stardoc over to bazelbuild/stardoc, which should complete before pushing fixes to additional bugs.

https://github.com/bazelbuild/skydoc/issues/187
