### ISSUE TITLE
Stardoc requires visibility on the main source file

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/skydoc#260]
Example from Skylib:

https://github.com/bazelbuild/bazel-skylib/blob/master/docs/BUILD

```starlark
stardoc(
    name = "collections_docs",
    out = "collections_doc_gen.md",
    input = "//lib:collections.bzl",
    deps = ["//lib:collections"],
)
```

This means that `//docs/BUILD` must be able to access `//lib:collections.bzl`. So it needs to be exported with `exports_files`. Stardoc shouldn't encourage the use of `exports_files`.

**Comment by achew22** [comment]
Are there any suggestions on how to get around this?
