### ISSUE TITLE
Fix build failure with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/skydoc#264]
In bazelbuild/bazel#11665, Bazel upgraded java_tools to v9.0 which has a new error prone version.

The build is failing with:
```
external/io_bazel/src/main/java/com/google/devtools/build/lib/concurrent/MultisetSemaphore.java:89: error: [PreconditionsInvalidPlaceholder] Preconditions only accepts the %s placeholder in error message strings
          "maxNumUniqueValues must be positive (was %d)",
          ^
    (see https://errorprone.info/bugpattern/PreconditionsInvalidPlaceholder)
  Did you mean '"maxNumUniqueValues must be positive (was %s)",'?
```
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1545#4758b2ef-d760-4922-9914-40a19de58f56

**Comment by davido** [comment]
@philwo @meteorcloudy 

I just checked: the problem reported by EP is a real bug, that was fixed in this CL: 

https://github.com/bazelbuild/bazel/commit/5d2305bd605327863fa12f529be2d7a7bfe55d55

For some reasons the outdated Bazel code is still referenced on the CI. Why would this be the case?

**Comment by meteorcloudy** [comment]
I suppose it's because we ping bazel repo to a commit here:
https://github.com/bazelbuild/skydoc/blob/92ef4078d90f3e96c9502872af069feb4e60b090/WORKSPACE#L28

**Comment by davido** [comment]
Well spotted, so may be we want update thus SHA1 to something that includes bazelbuild/bazel@5d2305b at least?

**Comment by meteorcloudy** [comment]
Yes, I'm trying. I'm hitting some build error of protobuf with io_bazel repo at 5d2305bd605327863fa12f529be2d7a7bfe55d55

**Comment by davido** [comment]
Is this because protobuf was updated in Bazel@HEAD?

**Comment by meteorcloudy** [comment]
Yes

**Comment by meteorcloudy** [comment]
OK, I found a workaround
