### ISSUE TITLE
Skydoc depends on protobuf.bzl in bazel_tools

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/skydoc#4]
As with bazelbuild/dash#12, this is now broken at HEAD since bazelbuild/bazel commit 285112c9b61ca3782e00ccf6411339da7291a3c3 removed protobuf from bazel_tools.

+cc @damienmg @lberki @kchodorow

**Comment by damienmg** [comment]
fwiw skydoc should depends on it through a dedicated remote repository (depends on the bazel repository). We specifically excluded it because people were relying on it too much

**Comment by davidzchen** [comment]
After thinking about it some more, I am thinking it might be better to remove this dependency altogether and define a custom set of proto messages for Skydoc. My reasoning is as follows:

* Skydoc only uses a few messages in `build.proto`, namely, `BuildLanguage`.
* I am working on adding support for parsing examples, default values, and implicit output targets, and it would be cleaner to be able to add fields to the protos to store this information
* The output protos of Skydoc is currently not being consumed by anything else in Bazel, so there is no need to share the same set of protos
* Removing this dependency would reduce the build time of Skydoc by avoiding having to download the Bazel dependency.

WDYT?

**Comment by damienmg** [comment]
That's is sensible. SGTM
