### ISSUE TITLE
Tests are failing on ci.bazel.io

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/skydoc#5]
See http://ci.bazel.io/job/skydoc/3/

**Comment by damienmg** [comment]
@davidzchen ping?

**Comment by davidzchen** [comment]
These should be fixed in the next push.

**Comment by damienmg** [comment]
Thanks!

**Comment by davidzchen** [comment]
What do the "HEAD" and "latest" Jenkins configurations refer to? Currently, the tests at HEAD are failing but latest is succeeding.

**Comment by damienmg** [comment]
HEAD = Bazel @HEAD
latest = Latest release of Bazel

**Comment by damienmg** [comment]
Well tests are fixed, the problem @HEAD is not from skydoc
