### ISSUE TITLE
feature request: tar output

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/skydoc#56]
`skylark_doc` produces a ZIP file containing the generated documentation.  It would be useful if it could instead produce a TAR archive.  That would be more compatible with consuming rules, such as `docker_build`; unpacking TARs as inputs seems to be more common in the bazel ecosystem than ZIPs.

**Comment by aiuto** [comment]
What I would suggest instead is that Skydoc produces a directory of files and that the user can then compose that with a tar or zip (or cpio?) package rule to get the desired bundle format.
