### ISSUE TITLE
skydoc code doesn't run under Python 3

### ISSUE THREAD

**Issue by duggelz** [bazelbuild/skydoc#57]
To reproduce, use the new `--python_path` flag to force Python 3:

```
bazel test --python_path=/usr/bin/python3 //...
```

Gives an error message shown below:

```
ERROR: /path/skydoc/skylark/BUILD:5:1: Generating Skylark doc for skylark-docs (1 files) failed (Exit 1).
Traceback (most recent call last):
  File "/longpath/execroot/io_bazel_skydoc/bazel-out/host/bin/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/main.py", line 18, in <module>
    import gflags
  File "/longpath/execroot/io_bazel_skydoc/bazel-out/host/bin/skydoc/skydoc.runfiles/gflags_repo/gflags.py", line 1091
    except gflags_validators.Error, e:
                                  ^
SyntaxError: invalid syntax
```

**Comment by gpshead** [comment]
`gflags` is obsolete, skydoc needs to move to `absl.flags` from https://pypi.python.org/pypi/absl-py/ (https://github.com/abseil/abseil-py).

**Comment by qzmfranklin** [comment]
I have exactly the same issue. Would be very much looking forward to a resolution.

**Comment by meteorcloudy** [comment]
Is there any progress on this issue? @duggelz @c-parsons

**Comment by c-parsons** [comment]
The progress on this issue is that we have checked-in a full rewrite of skydoc, named "Stardoc" which uses java instead of python (and has some different properties)
Documentation and announcement forthcoming (there's an open pull request)

**Comment by meteorcloudy** [comment]
>The progress on this issue is that we have checked-in a full rewrite of skydoc, named "Stardoc" which uses java instead of python (and has some different properties)
Documentation and announcement forthcoming (there's an open pull request)

@alexeagle @filipesilva 
Currently Skydoc only works with Python 2. Sounds like we should update rules_nodejs to use the new Stardoc once it's ready?

**Comment by filipesilva** [comment]
@meteorcloudy that sounds like a good idea. 

Until repositories update to Stardoc though, shouldn't https://github.com/bazelbuild/continuous-integration Windows CI use python 2.7?

Or perhaps provide another way for repositories that want to test on Windows to specify the python version to use for some targets. 

Skydoc is part of `bazelbuild` and doesn't support python 3, so it's not a stretch to imagine some other repository does not support python 2. If a workspace needs to use both a python 2.7 and 3.7 incompatible repositories, they'd need both installed on the same machine and to provide different python paths for some targets. 

If a single python version must be chosen for `bazelbuild/continuous-integration` though, then it should be the most compatible one for `bazelbuild/*` repositories.

**Comment by philwo** [comment]
Fixed with https://github.com/bazelbuild/skydoc/pull/110 :)
