### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/skydoc#58]
I've run into issues with dependencies pulled in by `skydoc` in several repos I collaborate on, you can see a sample error [here](https://github.com/bazelbuild/rules_python/pull/6#issuecomment-330308720).

This being clean on Windows is blocking Windows support on at least `google/subpar` and `bazelbuild/rules_python`.  To be clear: we can comment this stuff out to uncover other issues, but we cannot enable Windows CI or declare support without this working.

@davidstanke @davidzchen @dslomov FYI.

**Comment by jin** [comment]
cc @laszlocsomor @spomorski

**Comment by laszlocsomor** [comment]
@alexeagle : what's an easy, simple way to repro?

**Comment by alexeagle** [comment]
@laszlocsomor run the skydoc examples on windows?

**Comment by alexeagle** [comment]
Note, the protobuf library and rules_sass now both succeed on windows. Now it's skydoc itself that fails because it doesn't handle lack of runfiles symlinks:

```
ERROR: C:/users/alexeagle/projects/rules_nodejs/docs/BUILD.bazel:17:1: Generating Skylark doc for docs (9 files) failed (Exit 1)
Traceback (most recent call last):
  File "c:\users\alexea~1\appdata\local\temp\Bazel.runfiles_qthyx8\runfiles\io_bazel_skydoc\skydoc\main.py", line 330, in <module>
    main(FLAGS(sys.argv))
  File "c:\users\alexea~1\appdata\local\temp\Bazel.runfiles_qthyx8\runfiles\io_bazel_skydoc\skydoc\main.py", line 322, in main
    html_writer = HtmlWriter(writer_options)
  File "c:\users\alexea~1\appdata\local\temp\Bazel.runfiles_qthyx8\runfiles\io_bazel_skydoc\skydoc\main.py", line 211, in __init__
    self.__options.link_ext)
  File "c:\users\alexea~1\appdata\local\temp\Bazel.runfiles_qthyx8\runfiles\io_bazel_skydoc\skydoc\main.py", line 73, in _create_jinja_environment
    loader=jinja2.FileSystemLoader(_runfile_path(TEMPLATE_PATH)),
  File "c:\users\alexea~1\appdata\local\temp\Bazel.runfiles_qthyx8\runfiles\io_bazel_skydoc\skydoc\main.py", line 117, in _runfile_path
    raise AssertionError('Cannot find .runfiles directory.')
AssertionError: Cannot find .runfiles directory.
Target //docs:docs failed to build
```

**Comment by laszlocsomor** [comment]
@alexeagle , could you tell me your repo's github link and what commit you checked out, so I can repro the same error? Which Bazel version did you use?

**Comment by alexeagle** [comment]
rules_nodejs master
run `bazel build //docs`
I think I was on Bazel 0.16
Note, this is low priority for me, and possibly we should fix it in the stardoc rewrite rather than here.

**Comment by filipesilva** [comment]
Using Windows 10, Bazel 0.17.1, skydoc at https://github.com/bazelbuild/skydoc/commit/d34c44c3f4102eb94beaf2636c6cf532f0ec1ee8, and running `bazel build //docs/...` on https://github.com/bazelbuild/rules_typescript shows the following log:

```
$ bazel build //docs/...
INFO: SHA256 (https://github.com/bazelbuild/skydoc/archive/d34c44c3f4102eb94beaf2636c6cf532f0ec1ee8.zip) = 720f61e8ad98b4f62bb80c65ec9a4a27918a91e6e3fdda2d999810b4c8cbf020
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //docs:docs (32 packages loaded).
INFO: Found 1 target...
ERROR: D:/work/rules_typescript/docs/BUILD.bazel:3:1: Generating Skylark doc for docs (6 files) failed (Exit 1)
Traceback (most recent call last):
  File "\\?\C:\Users\kamik\AppData\Local\Temp\Bazel.runfiles__u5q6cm5\runfiles\io_bazel_skydoc\skydoc\main.py", line 18, in <module>
    import gflags
  File "\\?\C:\Users\kamik\AppData\Local\Temp\Bazel.runfiles__u5q6cm5\runfiles\gflags_repo\gflags.py", line 1091
    except gflags_validators.Error, e:
                                  ^
SyntaxError: invalid syntax
Target //docs:docs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.451s, Critical Path: 0.97s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by laszlocsomor** [comment]
@alexeagle , thanks, that helped! I could repro the issue and fix it in Skydoc. I'll send a PR shortly. I can now build `//docs/...` at https://github.com/bazelbuild/rules_nodejs/commit/62d309aed7769ddbb6709b0d8109d0f4718fb635

**Comment by laszlocsomor** [comment]
@filipesilva : With https://github.com/bazelbuild/skydoc/pull/108 in my local copy of skydoc, and `rules_typescript/package.bzl` modified to load `skydoc` from my copy, I can build `//docs/...` at https://github.com/bazelbuild/rules_typescript/commit/799e364e25b67645e099a87a04cef923f8ee6fdb

**Comment by laszlocsomor** [comment]
I'm using 0.17.1 on Windows 10

**Comment by laszlocsomor** [comment]
@filipesilva : Which Python version are you using? The error in https://github.com/bazelbuild/skydoc/issues/58#issuecomment-423480176 looks like a python incompatibility issue.

**Comment by laszlocsomor** [comment]
Yes, indeed the Python version is the issue. I can build when I put Python 2 on the PATH, but I get the same error as https://github.com/bazelbuild/skydoc/issues/58#issuecomment-423480176 with Python 3.

**Comment by laszlocsomor** [comment]
@filipesilva : Bazel can use both major versions of Python, but apparently the Skydoc python scripts were written for 2. I'm not happy to say this, but frankly it's probably less likely to see such breakages if you use Python 2. (That said, from now I'll make sure to always use Py 3 for my own builds to ensure all my scripts are compatible.)

**Comment by filipesilva** [comment]
@laszlocsomor that indeed is unfortunate but personally it makes no difference to use 2.7 or 3.7 so I will use 2.7.

I tried running your https://github.com/bazelbuild/rules_typescript/pull/282 PR locally and it does finish successfully on Windows.

However, CI shows it seems to fail on everything but windows...
```
ERROR: /home/circleci/ts/docs/BUILD.bazel:3:1: Generating Skylark doc for docs (6 files) failed (Exit 1)

Traceback (most recent call last):
  File "/home/circleci/.cache/bazel/_bazel_circleci/143962326f06c2543998f9d4c1332492/sandbox/processwrapper-sandbox/476/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/main.py", line 324, in <module>
    main(FLAGS(sys.argv))
  File "/home/circleci/.cache/bazel/_bazel_circleci/143962326f06c2543998f9d4c1332492/sandbox/processwrapper-sandbox/476/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/main.py", line 317, in main
    html_writer.write(rulesets)
  File "/home/circleci/.cache/bazel/_bazel_circleci/143962326f06c2543998f9d4c1332492/sandbox/processwrapper-sandbox/476/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/main.py", line 213, in write
    '%s' % CSS_FILE)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: '/home/circleci/.cache/bazel/_bazel_circleci/143962326f06c2543998f9d4c1332492/sandbox/processwrapper-sandbox/476/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfile/io_bazel_skydoc/skydoc/sass/main.css'
INFO: Elapsed time: 98.490s, Critical Path: 35.30s
```

**Comment by filipesilva** [comment]
@laszlocsomor I tried using the updated skydoc on rules_typescript/rules_nodejs (as a followup to your PRs) and also ran into into the python issue there:

- https://github.com/bazelbuild/rules_typescript/pull/284
- https://buildkite.com/bazel/rules-typescript-typescript/builds/648#2a953cff-3d4a-4707-af87-5c1d19fcf648
```
ERROR: D:/build/buildkite-worker-windows-java8-gd7t-1/bazel/rules-typescript-typescript/docs/BUILD.bazel:3:1: Couldn't build file docs/docs-skydoc.zip: Generating Skylark doc for docs (6 files) failed (Exit 1)
--
  | Traceback (most recent call last):
  | File "\\?\D:\temp\Bazel.runfiles_o6rauhqd\runfiles\io_bazel_skydoc\skydoc\main.py", line 19, in <module>
  | import gflags
  | File "\\?\D:\temp\Bazel.runfiles_o6rauhqd\runfiles\gflags_repo\gflags.py", line 1091
  | except gflags_validators.Error, e:
```

This is the same error I saw above when using Python 3.7, which I guess means https://github.com/bazelbuild/continuous-integration is using that version as well. 

Also cc @meteorcloudy since last time something was needed in the CI setup (https://github.com/bazelbuild/bazel-gazelle/issues/321#issuecomment-423519381) he took care of it.

**Comment by meteorcloudy** [comment]
I got this error after upgrading gflag in Skydoc
```
ERROR: C:/tools/msys64/home/pcloudy/workspace/rules_nodejs/docs/BUILD.bazel:17:1: Generating Skylark doc for docs (9 files) failed (Exit 1)
Traceback (most recent call last):
  File "\\?\C:\Users\pcloudy\AppData\Local\Temp\Bazel.runfiles_6ijdo96u\runfiles\io_bazel_skydoc\skydoc\main.py", line 329, in <module>
    main(FLAGS(sys.argv))
  File "\\?\C:\Users\pcloudy\AppData\Local\Temp\Bazel.runfiles_6ijdo96u\runfiles\io_bazel_skydoc\skydoc\main.py", line 297, in main
    load_symbols = load_sym_extractor.extract(bzl_file)
  File "\\?\C:\Users\pcloudy\AppData\Local\Temp\Bazel.runfiles_6ijdo96u\runfiles\io_bazel_skydoc\skydoc\load_extractor.py", line 110, in extract
    load_symbols = self._extract_loads(bzl_file)
  File "\\?\C:\Users\pcloudy\AppData\Local\Temp\Bazel.runfiles_6ijdo96u\runfiles\io_bazel_skydoc\skydoc\load_extractor.py", line 66, in _extract_loads
    for alias, symbol in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```
Looks like Skydoc itself need to fix Python3 compatibility

**Comment by filipesilva** [comment]
@meteorcloudy should the bazel CI move to use Python 2.7 then?

**Comment by meteorcloudy** [comment]
@filipesilva Just confirmed we don't have Python2 installed in Windows slaves on our CI. I think the best way to go here is to make Skydoc Python3 compatible. I can investigate to see how difficult it would be.

/cc @c-parsons
