### ISSUE TITLE
Commit 4b71d2e1bc3afa0ce0a5b6e68dac3c559654d975 of Bazel enforce workspace name which breaks skydoc

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/skydoc#7]
skydoc should have a workspace name and fix the various imports.

/cc @davidzchen

**Comment by kchodorow** [comment]
This has actually been fixed internally, it just needs to be pushed.

**Comment by damienmg** [comment]
pushing change the failure mode but did not fixed it:
http://ci.bazel.io/job/skydoc/37/

**Comment by damienmg** [comment]
Oh nice, the new failures are with 0.2.2b not with HEAD.

**Comment by kchodorow** [comment]
Yeah, I'm looking to see if I can do something similar to what I did with tensorflow/serving for skydoc.

**Comment by kchodorow** [comment]
Got it! 0.2.2b was way before cache invalidation on workspace name change was fixed, so the CI needs a bazel clean (just `bazel clean` should be sufficient, they shouldn't need an `--expunge`). Even thought the errors are different between darwin/linux, the solution to both is a `bazel clean`.

**Comment by damienmg** [comment]
I had to clean expunge and it fixes the ubuntu machine. Now I need to do the same on the mac machine.

FTR I did the following to clean expunge:
```
 for i in "" -2 -3 -4; do for f in 14-04 15-10; do gcloud compute ssh --zone $(gcloud compute instances list -r ubuntu-$f-slave$i | tail -1 | cut -d " " -f 2) ubuntu-$f-slave$i "sudo su -s /bin/bash ci -c 'cd /home/ci/workspace/skydoc/BAZEL_VERSION/latest/PLATFORM_NAME/linux-x86_64 &&/home/ci/.bazel/latest/bin/bazel clean --expunge; cd /home/ci/workspace/skydoc/BAZEL_VERSION/latest/PLATFORM_NAME/ubuntu_15.10-x86_64 && /home/ci/.bazel/latest/bin/bazel clean --expunge'" ; done; done

```

**Comment by damienmg** [comment]
Fixed the mac now everything should be good to go hopefully.

**Comment by damienmg** [comment]
And this is fixed!
