### ISSUE TITLE
toolchain attribute on rules cause Skydoc to fall over.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/skydoc#89]
I am adding toolchains to rules_kotlin and skydoc considers not recognising the toolchain attribute on a `rule()` a terminal condition -- there isn't a work around for this for #71 we can simply not use new rule modelling features.

In general skydoc needs a bit of work to be suitable for large rule repos. Is such work planned or am I better of switching to RST ?

**Comment by mboes** [comment]
Fixed in PR #86. See https://github.com/mboes/skydoc/commits/master, which integrates a number of fixes relevant for larger rule sets. Also, the codebase is quite hackable IME, so don't hesitate to dive in if you find an issue!

**Comment by hsyed** [comment]
Thanks !

**Comment by hsyed** [comment]
@mboes how do we get this merged in ? there are quote a few open PR's

**Comment by jin** [comment]
@davidzchen are you the current owner of Skydoc?
