### ISSUE TITLE
Please move from native to Skylark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/skydoc#98]
Bazel is planning to move away from native rules for external repositories to Skylark rules, mainly because bundling every version control system in bazel does not scale. As part of this effort, we plan to submit https://bazel-review.googlesource.com/c/bazel/+/55932 soon, which will cause bazel by default to insist that the skylark versions the git and http rules for external repositories be used. This can be disabled by a flag for at least the next 6 months, but we still would appreciate if you could adopt your repository to use the Skylark versions of those rules soon.

A test run of downstream projects with that flag flip in bazel enabled can be found at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/286

For more background, see
- the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Thanks.

**Comment by mhlopko** [comment]
I don't think this is fixed: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/531#52c693a7-0b2e-43a9-bfa3-91a34ebe13c1. Please fix quickly and create an issue at bazelbuild/continuous-integration to reenable. Keep in mind that we are not catching unintentional breakages of this project in bazel@HEAD.

**Comment by meteorcloudy** [comment]
Skydoc is still failing on CI with Bazel@HEAD:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/544#a5702bcb-7db7-4711-9e26-ced16c851ccf
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/43c71d16733ef2d8a342e784e0a31963/external/jinja2_archive/BUILD.bazel:2:1: no such package '@markupsafe_archive//': The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
--
  | Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule. and referenced by '@jinja2_archive//:jinja2'


```

**Comment by meteorcloudy** [comment]
@c-parsons Thanks for the fix!
